language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # minimum rustc version
    - rust: 1.28.0
      script: cargo build

script:
  - cargo test
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --benches; fi'

notifications:
  email:
    on_success: never
