language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    # `tls` feature
    - rust: stable
      script: cargo test --features tls

script:
  - cargo test
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --benches; fi'

notifications:
  email:
    on_success: never
